### PR TITLE
[#2369] fix(spark): Potential race condition on reading prefetch

### LINKED ISSUE #2369: [Bug] Race condition when using the prefetchableClientReadHandler
### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Image

The bug happens on the code.https://github.com/apache/incubator-uniffle/blob/124a9015835bf30e47bb16d584b065bea06f01e9/storage/src/main/java/org/apache/uniffle/storage/handler/impl/DataSkippableReadHandler.java#L90-L110

The `processedBlockId` will be modified in the ShuffleReadClientImpl at the same time.

If so, we have to use synchronize to lock all related `processBlockId` operations.

### Affects Version(s)

master

### Uniffle Server Log Output

```logtalk

```

### Uniffle Engine Log Output

```logtalk

```

### Uniffle Server Configurations

```yaml

```

### Uniffle Engine Configurations

```yaml

```

### Additional context

cc @jerqi 

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by zuston**
### What changes were proposed in this pull request?

fix potential race condition on reading prefetch

### Why are the changes needed?

fix #2369

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Exsiting tests

### CODE REVIEW

File: common/src/main/java/org/apache/uniffle/common/util/RssUtils.java [hunk 1]
```diff
@@ -272,6 +273,29 @@ public static Roaring64NavigableMap cloneBitMap(Roaring64NavigableMap bitmap) {
     return clone;
   }
 
+  public static Roaring64NavigableMap toBitmap(Set<Long> sets) {
```
Comment (jerqi) [inline common/src/main/java/org/apache/uniffle/common/util/RssUtils.java:276]: Could we wrap the the bitmap as a set to avoid unnecessary convention?

Comment (zuston) [reply common/src/main/java/org/apache/uniffle/common/util/RssUtils.java:276]: It will be invoked by only one side. and it's not a hot point. Maybe this is not necessary

**Comment by zuston** [comment]
Gentle ping @jerqi

**Review by jerqi — APPROVED** [review]

**Comment by zuston** [comment]
Merge this. And the async read speed up tracking will be shown in the spark UI in the future
