### PR TITLE
[#2466] fix(server): Ignore appIdToInfos when serialize ServerNode

### LINKED ISSUE #2466: [Bug] failed on ServerNode json serialization
### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [x] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

`appIdToInfos` in `ServerNode` can not be serialized. This causes  the node list can not display on the dashboard website.

### Affects Version(s)

master/0.10

### Uniffle Server Log Output

```logtalk
[2025-04-27 17:35:25.881] [Jetty-167] [WARN] ServletHandler -
javax.servlet.ServletException: org.apache.hbase.thirdparty.org.glassfish.jersey.server.ContainerException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.google.protobuf.UnknownFieldSet$Parser and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.apache.uniffle.common.web.resource.Response["data"]->java.util.ArrayList[0]->org.apache.uniffle.coordinator.ServerNode["appIdToInfos"]->java.util.concurrent.ConcurrentHashMap["application_1710412492003_168142378_1745746426063"]->org.apache.uniffle.proto.RssProtos$ApplicationInfo["unknownFields"]->com.google.protobuf.UnknownFieldSet["parserForType"])
        at org.apache.hbase.thirdparty.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
        at org.apache.hbase.thirdparty.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.apache.hbase.thirdparty.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
        at org.apache.hbase.thirdparty.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
        at org.apache.hbase.thirdparty.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
```

### Uniffle Engine Log Output

```logtalk

```

### Uniffle Server Configurations

```yaml

```

### Uniffle Engine Configurations

```yaml

```

### Additional context

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xianjingfeng**
### What changes were proposed in this pull request?

Ignore appIdToInfos when serialize ServerNode

### Why are the changes needed?

Fix #2466

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual Testing

### CODE REVIEW

File: coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java [hunk 1]
```diff
@@ -51,7 +52,7 @@ public class ServerNode implements Comparable<ServerNode> {
   private long startTime = -1;
   private String version;
   private String gitCommitId;
-  Map<String, RssProtos.ApplicationInfo> appIdToInfos;
+  @JsonIgnore Map<String, RssProtos.ApplicationInfo> appIdToInfos;
```
Comment (jerqi) [inline coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java:55]: Why do we need this?

Comment (xianjingfeng) [reply coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java:55]: `RssProtos.ApplicationInfo` can't be serialized. if `appIdToInfos` is not empty, we can't see any node in the dashboard ui.

**Review by jerqi — APPROVED** [review]

File: coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java (hunk 1 above)
Comment (jerqi) [reply coordinator/src/main/java/org/apache/uniffle/coordinator/ServerNode.java:55]: I got it
